// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDruv-ncxvwhBJsVmCYC6cDUNvacscgu8U',
    appId: '1:452406313117:web:8dbe8b15064da6736f5474',
    messagingSenderId: '452406313117',
    projectId: 'flutter-dc-853df',
    authDomain: 'flutter-dc-853df.firebaseapp.com',
    storageBucket: 'flutter-dc-853df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Zt910dNBJZdpowRdf5a3EwF-rmKv47k',
    appId: '1:452406313117:android:fcc030fb4a1d88506f5474',
    messagingSenderId: '452406313117',
    projectId: 'flutter-dc-853df',
    storageBucket: 'flutter-dc-853df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV8UudIyzE-azGjY-AcKpSb3ag0mVXqsE',
    appId: '1:452406313117:ios:fbde9e9163b27d8c6f5474',
    messagingSenderId: '452406313117',
    projectId: 'flutter-dc-853df',
    storageBucket: 'flutter-dc-853df.appspot.com',
    iosClientId: '452406313117-1df89jcor3480f4830artem4qm0da2s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.designcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV8UudIyzE-azGjY-AcKpSb3ag0mVXqsE',
    appId: '1:452406313117:ios:fbde9e9163b27d8c6f5474',
    messagingSenderId: '452406313117',
    projectId: 'flutter-dc-853df',
    storageBucket: 'flutter-dc-853df.appspot.com',
    iosClientId: '452406313117-1df89jcor3480f4830artem4qm0da2s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.designcode',
  );
}
